$basePath = 'C:\Users\seyda\source\repos\seydakaratekeli\KamPay3\KamPay\Services'
function Move-ServiceFile {
    param([string]$File, [string]$DestFolder)
    $fullPath = Join-Path $basePath $File
    $destPath = Join-Path $basePath $DestFolder
    if (Test-Path $fullPath) {
        if (!(Test-Path $destPath)) { New-Item -ItemType Directory -Force -Path $destPath | Out-Null }
        Move-Item -Path $fullPath -Destination $destPath -Force
        Write-Host "Moved $File to $DestFolder"
    }
}
Move-ServiceFile 'CacheCoordinator.cs' 'Caching'
Move-ServiceFile 'CacheManager.cs' 'Caching'
Move-ServiceFile 'ICacheCoordinator.cs' 'Caching'
Move-ServiceFile 'EmailService.cs' 'Email'
Move-ServiceFile 'EmailSettings.cs' 'Email'
Move-ServiceFile 'IEmailService.cs' 'Email'
Move-ServiceFile 'FirebaseCategoryService.cs' 'Categories'
Move-ServiceFile 'ICategoryService.cs' 'Categories'
Move-ServiceFile 'FirebaseFavoriteService.cs' 'Favorites'
Move-ServiceFile 'IFavoriteService.cs' 'Favorites'
Move-ServiceFile 'FirebaseGoodDeedService.cs' 'Features'
Move-ServiceFile 'GoodDeedService.cs' 'Features'
Move-ServiceFile 'IGoodDeedService.cs' 'Features'
Move-ServiceFile 'FirebaseSurpriseBoxService.cs' 'Features'
Move-ServiceFile 'ISurpriseBoxService.cs' 'Features'
Move-ServiceFile 'FirebaseNotificationService.cs' 'Notifications'
Move-ServiceFile 'INotificationCoordinator.cs' 'Notifications'
Move-ServiceFile 'INotificationService.cs' 'Notifications'
Move-ServiceFile 'NotificationCoordinator.cs' 'Notifications'
Move-ServiceFile 'FirebaseObserverService.cs' 'Realtime'
Move-ServiceFile 'IRealtimeSnapshotService.cs' 'Realtime'
Move-ServiceFile 'RealtimeSnapshotService.cs' 'Realtime'
Move-ServiceFile 'FirebaseStorageService.cs' 'Storage'
Move-ServiceFile 'IStorageService.cs' 'Storage'
Move-ServiceFile 'FirebaseUserProfileService.cs' 'Profile'
Move-ServiceFile 'IUserProfileService.cs' 'Profile'
Move-ServiceFile 'IUserStateService.cs' 'Profile'
Move-ServiceFile 'UserStateService.cs' 'Profile'
Move-ServiceFile 'ILocalizationService.cs' 'Localization'
Move-ServiceFile 'LocalizationResourceManager.cs' 'Localization'
Move-ServiceFile 'IMessageCommandService.cs' 'Messaging'
Move-ServiceFile 'IMessageMediaCoordinator.cs' 'Messaging'
Move-ServiceFile 'IMessageQueryService.cs' 'Messaging'
Move-ServiceFile 'MessageMediaCoordinator.cs' 'Messaging'
Move-ServiceFile 'CustomerRequestManager.cs' 'ServiceSharing'
Move-ServiceFile 'ICustomerRequestManager.cs' 'ServiceSharing'
Move-ServiceFile 'IProviderProposalManager.cs' 'ServiceSharing'
Move-ServiceFile 'ProviderProposalManager.cs' 'ServiceSharing'
Move-ServiceFile 'IServiceSharingService.cs' 'ServiceSharing'
Move-ServiceFile 'FirebaseTransactionHistoryService.cs' 'Transactions'
Move-ServiceFile 'ITransactionHistoryService.cs' 'Transactions'
Move-ServiceFile 'ITransactionOrchestrator.cs' 'Transactions'
Move-ServiceFile 'TransactionOrchestrator.cs' 'Transactions'
Move-ServiceFile 'IServiceTypeHandler.cs' 'Handlers'
Move-ServiceFile 'ServiceTypeHandlerFactory.cs' 'Handlers'
Move-ServiceFile 'IReverseGeocodeService.cs' 'Location'
Move-ServiceFile 'ReverseGeocodeService.cs' 'Location'
Move-ServiceFile 'ProductCreationCoordinator.cs' 'Products\Coordinators'
Move-ServiceFile 'ProductImageCoordinator.cs' 'Products\Coordinators'
Move-ServiceFile 'IProductValidationService.cs' 'Products\Validation'
Move-ServiceFile 'IValidationCoordinator.cs' 'Products\Validation'
Move-ServiceFile 'ValidationCoordinator.cs' 'Products\Validation'
