//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamPay.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamPay.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Kabul Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teklif Kabul Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AcceptOffer {
            get {
                return ResourceManager.GetString("AcceptOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beğendiğiniz ürünleri favorilere ekleyerek kolayca erişebilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddFavoritesHint {
            get {
                return ResourceManager.GetString("AddFavoritesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   📷 Görsel Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorilere Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tümü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygula benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Hizmetler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AvailableServices {
            get {
                return ResourceManager.GetString("AvailableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rozet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bebek Ürünleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryBaby {
            get {
                return ResourceManager.GetString("CategoryBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap ve Kırtasiye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryBooks {
            get {
                return ResourceManager.GetString("CategoryBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizlik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryCleaning {
            get {
                return ResourceManager.GetString("CategoryCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giyim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryClothing {
            get {
                return ResourceManager.GetString("CategoryClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elektronik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryElectronics {
            get {
                return ResourceManager.GetString("CategoryElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun ve Hobi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryGames {
            get {
                return ResourceManager.GetString("CategoryGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bahçe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryGarden {
            get {
                return ResourceManager.GetString("CategoryGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ev Eşyası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryHomeGoods {
            get {
                return ResourceManager.GetString("CategoryHomeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryLesson {
            get {
                return ResourceManager.GetString("CategoryLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müzik Aletleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryMusic {
            get {
                return ResourceManager.GetString("CategoryMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryRepair {
            get {
                return ResourceManager.GetString("CategoryRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spor Malzemeleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategorySports {
            get {
                return ResourceManager.GetString("CategorySports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taşıma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryTransport {
            get {
                return ResourceManager.GetString("CategoryTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filtreleri değiştirin veya aramayı temizleyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChangeFiltersHint {
            get {
                return ResourceManager.GetString("ChangeFiltersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil fotoğrafını değiştirmek ister misin? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChangePhotoQuestion {
            get {
                return ResourceManager.GetString("ChangePhotoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sohbet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yorum Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Topluluk Paylaşımları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CommunityPosts {
            get {
                return ResourceManager.GetString("CommunityPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmeti Tamamla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CompleteService {
            get {
                return ResourceManager.GetString("CompleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConditionFair {
            get {
                return ResourceManager.GetString("ConditionFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İyi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConditionGood {
            get {
                return ResourceManager.GetString("ConditionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConditionLabel {
            get {
                return ResourceManager.GetString("ConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Gibi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConditionLikeNew {
            get {
                return ResourceManager.GetString("ConditionLikeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanılabilir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConditionUsable {
            get {
                return ResourceManager.GetString("ConditionUsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çok İyi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConditionVeryGood {
            get {
                return ResourceManager.GetString("ConditionVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onayla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silmek istediğinize emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünü silmek istediğinize emin misiniz? Bu işlem geri alınamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConfirmDeleteProduct {
            get {
                return ResourceManager.GetString("ConfirmDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış yapmak istediğinize emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünü satıldı olarak işaretlemek istediğinize emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConfirmMarkAsSold {
            get {
                return ResourceManager.GetString("ConfirmMarkAsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslim Aldım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConfirmReceived {
            get {
                return ResourceManager.GetString("ConfirmReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🎉 Tebrikler! 🎉 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim kurulamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContactFailed {
            get {
                return ResourceManager.GetString("ContactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paylaşılamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CouldNotShare {
            get {
                return ResourceManager.GetString("CouldNotShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Puanınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CurrentPoints {
            get {
                return ResourceManager.GetString("CurrentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   gün önce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarıyla silindi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silme başarısız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TESLİM EDİLDİ ✔️ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslimat Onayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DeliveryConfirmation {
            get {
                return ResourceManager.GetString("DeliveryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslimat QR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DeliveryQR {
            get {
                return ResourceManager.GetString("DeliveryQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demo Kullanıcı Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DemoUserInfo {
            get {
                return ResourceManager.GetString("DemoUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu ürünü Sürpriz Kutu&apos;ya bağışla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DonateSurpriseBox {
            get {
                return ResourceManager.GetString("DonateSurpriseBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre (Saat) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünü Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profili Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta doğrulama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EmailVerification {
            get {
                return ResourceManager.GetString("EmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni adınızı girin: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterNewFirstName {
            get {
                return ResourceManager.GetString("EnterNewFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni soyadınızı girin: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterNewLastName {
            get {
                return ResourceManager.GetString("EnterNewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni kullanıcı adınızı girin: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterNewUsername {
            get {
                return ResourceManager.GetString("EnterNewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-postanıza gönderilen 6 haneli kodu girin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takas benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takas Tercihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExchangePreference {
            get {
                return ResourceManager.GetString("ExchangePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sahte ürün benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FakeProduct {
            get {
                return ResourceManager.GetString("FakeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favoriler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favoriler yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FavoritesLoading {
            get {
                return ResourceManager.GetString("FavoritesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favoriler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ücret benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FeeLabel {
            get {
                return ResourceManager.GetString("FeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen tüm alanları doldurun benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filtrele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filtrele ve Sırala benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilterAndSort {
            get {
                return ResourceManager.GetString("FilterAndSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satılık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜCRETSİZ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İyilik Panosu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GoodDeedBoard {
            get {
                return ResourceManager.GetString("GoodDeedBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İyilik Panosu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GoodDeedBoardTitle {
            get {
                return ResourceManager.GetString("GoodDeedBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zaten hesabınız var? Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HaveAccountLogin {
            get {
                return ResourceManager.GetString("HaveAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Sayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   saat önce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygunsuz içerik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InappropriateContent {
            get {
                return ResourceManager.GetString("InappropriateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelen Teklifler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IncomingOffers {
            get {
                return ResourceManager.GetString("IncomingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelen Talepler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IncomingRequests {
            get {
                return ResourceManager.GetString("IncomingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetersiz puan! Daha fazla puan kazanmak için takas yapabilir veya ürün ekleyebilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InsufficientPoints {
            get {
                return ResourceManager.GetString("InsufficientPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz e-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Az önce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🌐 Language / Dil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LanguageDil {
            get {
                return ResourceManager.GetString("LanguageDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beğen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş yapılamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu işlem için giriş yapmalısınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ödeme Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MakePayment {
            get {
                return ResourceManager.GetString("MakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takas Teklif Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MakeTradeOffer {
            get {
                return ResourceManager.GetString("MakeTradeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Harita üzerine tıklayarak konumunuzu seçin veya 📍 butonuna basarak mevcut konumunuzu kullanın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MapLocationInfo {
            get {
                return ResourceManager.GetString("MapLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Harita açılamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MapOpenFailed {
            get {
                return ResourceManager.GetString("MapOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satıldı İşaretle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MarkAsSold {
            get {
                return ResourceManager.GetString("MarkAsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajlar yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MessagesLoading {
            get {
                return ResourceManager.GetString("MessagesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MessagesTitle {
            get {
                return ResourceManager.GetString("MessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dakika önce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yanıltıcı bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MisleadingInfo {
            get {
                return ResourceManager.GetString("MisleadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eksik bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MissingInfo {
            get {
                return ResourceManager.GetString("MissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlemlerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyActions {
            get {
                return ResourceManager.GetString("MyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rozetlerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyBadges {
            get {
                return ResourceManager.GetString("MyBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tekliflerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyOffers {
            get {
                return ResourceManager.GetString("MyOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Benim Ürünüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyProduct {
            get {
                return ResourceManager.GetString("MyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünlerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyProducts {
            get {
                return ResourceManager.GetString("MyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Bildirim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NewNotification {
            get {
                return ResourceManager.GetString("NewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hayır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesabın yok mu? Kayıt ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoAccountRegister {
            get {
                return ResourceManager.GetString("NoAccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz rozet kazanmadınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoBadgesYet {
            get {
                return ResourceManager.GetString("NoBadgesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz veri yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoDataYet {
            get {
                return ResourceManager.GetString("NoDataYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz favori ürününüz yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoFavoritesYet {
            get {
                return ResourceManager.GetString("NoFavoritesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz gelen bir teklif yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoIncomingOffers {
            get {
                return ResourceManager.GetString("NoIncomingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz size gelen bir hizmet talebi yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoIncomingRequests {
            get {
                return ResourceManager.GetString("NoIncomingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz mesajınız yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoMessagesYet {
            get {
                return ResourceManager.GetString("NoMessagesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz mesaj yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoMessageYet {
            get {
                return ResourceManager.GetString("NoMessageYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz bildirim yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoNotificationsYet {
            get {
                return ResourceManager.GetString("NoNotificationsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz yaptığınız bir teklif yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoOutgoingOffers {
            get {
                return ResourceManager.GetString("NoOutgoingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz gönderdiğiniz bir hizmet talebi yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoOutgoingRequests {
            get {
                return ResourceManager.GetString("NoOutgoingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arama kriterlerinize uygun ürün bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoProductsFound {
            get {
                return ResourceManager.GetString("NoProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Henüz ürün eklemediniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoProductsYet {
            get {
                return ResourceManager.GetString("NoProductsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sonuç bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bildirimler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belirtilmemiş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teklifler yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OffersLoading {
            get {
                return ResourceManager.GetString("OffersLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teklifler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OffersTitle {
            get {
                return ResourceManager.GetString("OffersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🎁 100 Puana Kutu Aç! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenBoxFor100Points {
            get {
                return ResourceManager.GetString("OpenBoxFor100Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürpriz kutunuz açılıyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpeningBox {
            get {
                return ResourceManager.GetString("OpeningBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem başarısız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer Ürün benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OtherProduct {
            get {
                return ResourceManager.GetString("OtherProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giden Teklifler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OutgoingOffers {
            get {
                return ResourceManager.GetString("OutgoingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giden Talepler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OutgoingRequests {
            get {
                return ResourceManager.GetString("OutgoingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre Tekrar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreler eşleşmiyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fotoğraf yüklenemedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PhotoUploadFailed {
            get {
                return ResourceManager.GetString("PhotoUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İlan Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostTypeAnnouncement {
            get {
                return ResourceManager.GetString("PostTypeAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yardım Talebi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostTypeHelpRequest {
            get {
                return ResourceManager.GetString("PostTypeHelpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teklif benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostTypeOffer {
            get {
                return ResourceManager.GetString("PostTypeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talep benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostTypeRequest {
            get {
                return ResourceManager.GetString("PostTypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teşekkür benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostTypeThankYou {
            get {
                return ResourceManager.GetString("PostTypeThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönüllü Aranıyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PostTypeVolunteer {
            get {
                return ResourceManager.GetString("PostTypeVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hepsi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceAll {
            get {
                return ResourceManager.GetString("PriceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceAscending {
            get {
                return ResourceManager.GetString("PriceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Azalan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceDescending {
            get {
                return ResourceManager.GetString("PriceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat (₺) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat sıralama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceSorting {
            get {
                return ResourceManager.GetString("PriceSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat (₺) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceTL {
            get {
                return ResourceManager.GetString("PriceTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem yapılıyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductCondition {
            get {
                return ResourceManager.GetString("ProductCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün silindi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Açıklaması benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Detayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Görselleri (Maksimum 5) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductImages {
            get {
                return ResourceManager.GetString("ProductImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün yüklenirken hata oluştu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductLoadError {
            get {
                return ResourceManager.GetString("ProductLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün satıldı olarak işaretlendi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductMarkedAsSold {
            get {
                return ResourceManager.GetString("ProductMarkedAsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Başlığı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductTypeDonation {
            get {
                return ResourceManager.GetString("ProductTypeDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takas benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductTypeExchange {
            get {
                return ResourceManager.GetString("ProductTypeExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satılık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductTypeSale {
            get {
                return ResourceManager.GetString("ProductTypeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil Fotoğrafı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProfilePhoto {
            get {
                return ResourceManager.GetString("ProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil güncellendi! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayın Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR Kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TESLİM ALINDI ✔️ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reddet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teklif Reddet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RejectOffer {
            get {
                return ResourceManager.GetString("RejectOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beni hatırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorilerden Çıkar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🚩 Şikayet Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şikayet Nedeni benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReportReason {
            get {
                return ResourceManager.GetString("ReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şikayetiniz alındı. İnceleme süreci başlatıldı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReportReceived {
            get {
                return ResourceManager.GetString("ReportReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talep Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talep Eden: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RequestedBy {
            get {
                return ResourceManager.GetString("RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kodu Tekrar Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarıyla kaydedildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydediliyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Karşı Tarafın Kodunu Tara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScanOtherCode {
            get {
                return ResourceManager.GetString("ScanOtherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR Kod Tara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslimatı onaylamak için QR kodu kameraya okutun. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScanQRInstruction {
            get {
                return ResourceManager.GetString("ScanQRInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR Kod Tara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScanQRTitle {
            get {
                return ResourceManager.GetString("ScanQRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sohbetlerde ara... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SearchInChats {
            get {
                return ResourceManager.GetString("SearchInChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün ara... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ne arıyorsunuz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SearchProducts {
            get {
                return ResourceManager.GetString("SearchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet ara... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SearchService {
            get {
                return ResourceManager.GetString("SearchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectCategoryFilter {
            get {
                return ResourceManager.GetString("SelectCategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectCategoryPost {
            get {
                return ResourceManager.GetString("SelectCategoryPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum Seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectCondition {
            get {
                return ResourceManager.GetString("SelectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🌐 Dil Seçin / Select Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni profil fotoğrafı seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectNewPhoto {
            get {
                return ResourceManager.GetString("SelectNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıralama Seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectSorting {
            get {
                return ResourceManager.GetString("SelectSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tip Seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satıcı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satıcı: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SellerName {
            get {
                return ResourceManager.GetString("SellerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İlk mesajı gönderin! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendFirstMessage {
            get {
                return ResourceManager.GetString("SendFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderiliyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesaj Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teklif Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendOffer {
            get {
                return ResourceManager.GetString("SendOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fotoğraf Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendPhoto {
            get {
                return ResourceManager.GetString("SendPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talep Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çocuk Bakımı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryChildcare {
            get {
                return ResourceManager.GetString("ServiceCategoryChildcare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryCooking {
            get {
                return ResourceManager.GetString("ServiceCategoryCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eğitim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryEducation {
            get {
                return ResourceManager.GetString("ServiceCategoryEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taşıma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryMoving {
            get {
                return ResourceManager.GetString("ServiceCategoryMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryOther {
            get {
                return ResourceManager.GetString("ServiceCategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evcil Hayvan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryPetCare {
            get {
                return ResourceManager.GetString("ServiceCategoryPetCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teknik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryTechnical {
            get {
                return ResourceManager.GetString("ServiceCategoryTechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çeviri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceCategoryTranslation {
            get {
                return ResourceManager.GetString("ServiceCategoryTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Açıklaması benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detaylar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceDetails {
            get {
                return ResourceManager.GetString("ServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Örneğin: Müzik dersi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceExample {
            get {
                return ResourceManager.GetString("ServiceExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Talebi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceRequest {
            get {
                return ResourceManager.GetString("ServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Talepleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceRequests {
            get {
                return ResourceManager.GetString("ServiceRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet talepleri yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceRequestsLoading {
            get {
                return ResourceManager.GetString("ServiceRequestsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Taleplerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceRequestsTitle {
            get {
                return ResourceManager.GetString("ServiceRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmetler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Paylaşımı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceSharingTitle {
            get {
                return ResourceManager.GetString("ServiceSharingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Başlığı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paylaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KamPay ile paylaşıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SharedWithKamPay {
            get {
                return ResourceManager.GetString("SharedWithKamPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni İyilik Paylaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShareNewGoodDeed {
            get {
                return ResourceManager.GetString("ShareNewGoodDeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Hizmet Paylaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShareNewService {
            get {
                return ResourceManager.GetString("ShareNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İlan Paylaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SharePost {
            get {
                return ResourceManager.GetString("SharePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profilimi Paylaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShareProfile {
            get {
                return ResourceManager.GetString("ShareProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmeti Paylaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShareService {
            get {
                return ResourceManager.GetString("ShareService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düşüncelerinizi paylaşın... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShareYourThoughts {
            get {
                return ResourceManager.GetString("ShareYourThoughts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR Kod Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShowQRCode {
            get {
                return ResourceManager.GetString("ShowQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıralama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bir ürün üzerinden mesajlaşmaya başlayabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StartChatFromProduct {
            get {
                return ResourceManager.GetString("StartChatFromProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100 puan karşılığında bir sürpriz kutu açarak bağışlanmış ürünlerden birini kazanma şansı yakala! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SurpriseBoxDescription {
            get {
                return ResourceManager.GetString("SurpriseBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürpriz Kutu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SurpriseBoxTitle {
            get {
                return ResourceManager.GetString("SurpriseBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre (Zaman Kredisi) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TimeCredit {
            get {
                return ResourceManager.GetString("TimeCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zaman Kredisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TimeCreditsLabel {
            get {
                return ResourceManager.GetString("TimeCreditsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konu Başlığı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TopicTitle {
            get {
                return ResourceManager.GetString("TopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam {0} rozet kazandınız! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TotalBadges {
            get {
                return ResourceManager.GetString("TotalBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajınızı yazın... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeMessage {
            get {
                return ResourceManager.GetString("TypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beklenmeyen hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarıyla güncellendi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı 1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string User1 {
            get {
                return ResourceManager.GetString("User1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı 2 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string User2 {
            get {
                return ResourceManager.GetString("User2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı bilgisi bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrula benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntülenme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🎁 Ürünümü Görmek İstiyorum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ViewMyProduct {
            get {
                return ResourceManager.GetString("ViewMyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONAY BEKLİYOR... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WaitingConfirmation {
            get {
                return ResourceManager.GetString("WaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satın Almak İste benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WantToBuy {
            get {
                return ResourceManager.GetString("WantToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Almak İstiyorum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WantToGet {
            get {
                return ResourceManager.GetString("WantToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uyarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoş geldiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoş geldiniz 👋 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ne ile takas yapmak istersiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WhatToExchange {
            get {
                return ResourceManager.GetString("WhatToExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yorum yaz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WriteComment {
            get {
                return ResourceManager.GetString("WriteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evet, Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
